apiVersion: v1
kind: Secret
metadata:
  name: stock-pipeline-secrets
type: Opaque
stringData:
  ALPHA_VANTAGE_API_KEY: "4T83VLC1FCBK1AUM"
  FINNHUB_API_KEY: "d6s2lapr01qpss2i4qm0d6s2lapr01qpss2i4qmg"
